### ISSUE TITLE
Blocky container error

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/k3s-gitops#29]
```yaml
Containers:
  blocky:
    Container ID:   docker://743473a790e9af0ce7f5fb68a6bb99420460b4ea94c6387eb1b11d0ebfec4227
    Image:          spx01/blocky:v0.5
    Image ID:       docker-pullable://spx01/blocky@sha256:51bb1df868cb5ace0a275abda6e1856681749df92910ce5af71d6c187d2ec755
    Ports:          4000/TCP, 53/TCP, 53/UDP
    Host Ports:     0/TCP, 0/TCP, 0/UDP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449
: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/c7fd0be2-d120-4b76-ad20-9110ff4b5d64/volume-s
ubpaths/config/blocky/0\\\" to rootfs \\\"/var/lib/docker/overlay2/22066adcc24fd62f2e160fefe9f249694ee41ba55dad4ae9246277f8d7a
439cb/merged\\\" at \\\"/var/lib/docker/overlay2/22066adcc24fd62f2e160fefe9f249694ee41ba55dad4ae9246277f8d7a439cb/merged/app/c
onfig.yml\\\" caused \\\"no such file or directory\\\"\"": unknown
```

Scaled service down to 0, and then scaled back to 2 and it's back online
