### ISSUE TITLE
Explore monitoring my Qnap NAS

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/k3s-gitops#41]
netdata or node_exporter or ?

**Comment by onedr0p** [comment]
Solved with node_exporter and using Qnap Container Station, deployed with the following yaml:

```
version: '3'
services:
  nodeexporter:
    image: prom/node-exporter:v0.18.1
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9100/metrics"]
      interval: 30s
      timeout: 20s
      retries: 3  
```
