### ISSUE TITLE
Nginx Ingress log spam

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/k3s-gitops#42]
Looks like using an IP in ExternalName for Services is creating a bunch of log spam in my nginx-ingress-controller logs

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: external-unifi-protect
spec:
  ports:
  - name: http
    port: 7443
  type: ExternalName
  externalName: 192.168.1.2
```

```
2020/04/01 12:50:34 [error] 1693#1693: *27130539 [lua] dns.lua:150: dns_lookup(): failed to query the DNS server for 192.168.1.2: server returned error code: 3: name error,  server returned error code: 3: name error
```
