### ISSUE TITLE
Investigate using proxy for caching container images

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/k3s-gitops#62]
Using a service like this would allow to cache container images not only from docker.io but quay.io and others

https://github.com/rpardini/docker-registry-proxy

I am unsure if this will work with containerd

See the current issue which makes this not possible with containerd

https://github.com/rancher/k3s/issues/2026

**Comment by onedr0p** [comment]
This is working great with nexus3.


```
devin@k3s-master:~$ cat /etc/rancher/k3s/registries.yaml
mirrors:
  "docker.io":
    endpoint:
      - "http://192.168.1.39:8082"
  "*":
    endpoint:
      - "http://192.168.1.39:8082"
```
